<?php
$quan_huyen = array(
    "0" => array("maqh"=>"001","name"=>"Quận Ba Đình","matp"=>"HANOI"),
    "1" => array("maqh"=>"002","name"=>"Quận Hoàn Kiếm","matp"=>"HANOI"),
    "2" => array("maqh"=>"003","name"=>"Quận Tây Hồ","matp"=>"HANOI"),
    "3" => array("maqh"=>"004","name"=>"Quận Long Biên","matp"=>"HANOI"),
    "4" => array("maqh"=>"005","name"=>"Quận Cầu Giấy","matp"=>"HANOI"),
    "5" => array("maqh"=>"006","name"=>"Quận Đống Đa","matp"=>"HANOI"),
    "6" => array("maqh"=>"007","name"=>"Quận Hai Bà Trưng","matp"=>"HANOI"),
    "7" => array("maqh"=>"008","name"=>"Quận Hoàng Mai","matp"=>"HANOI"),
    "8" => array("maqh"=>"009","name"=>"Quận Thanh Xuân","matp"=>"HANOI"),
    "9" => array("maqh"=>"016","name"=>"Huyện Sóc Sơn","matp"=>"HANOI"),
    "10" => array("maqh"=>"017","name"=>"Huyện Đông Anh","matp"=>"HANOI"),
    "11" => array("maqh"=>"018","name"=>"Huyện Gia Lâm","matp"=>"HANOI"),
    "12" => array("maqh"=>"019","name"=>"Quận Nam Từ Liêm","matp"=>"HANOI"),
    "13" => array("maqh"=>"020","name"=>"Huyện Thanh Trì","matp"=>"HANOI"),
    "14" => array("maqh"=>"021","name"=>"Quận Bắc Từ Liêm","matp"=>"HANOI"),
    "15" => array("maqh"=>"024","name"=>"Thành phố Hà Giang","matp"=>"HAGIANG"),
    "16" => array("maqh"=>"026","name"=>"Huyện Đồng Văn","matp"=>"HAGIANG"),
    "17" => array("maqh"=>"027","name"=>"Huyện Mèo Vạc","matp"=>"HAGIANG"),
    "18" => array("maqh"=>"028","name"=>"Huyện Yên Minh","matp"=>"HAGIANG"),
    "19" => array("maqh"=>"029","name"=>"Huyện Quản Bạ","matp"=>"HAGIANG"),
    "20" => array("maqh"=>"030","name"=>"Huyện Vị Xuyên","matp"=>"HAGIANG"),
    "21" => array("maqh"=>"031","name"=>"Huyện Bắc Mê","matp"=>"HAGIANG"),
    "22" => array("maqh"=>"032","name"=>"Huyện Hoàng Su Phì","matp"=>"HAGIANG"),
    "23" => array("maqh"=>"033","name"=>"Huyện Xín Mần","matp"=>"HAGIANG"),
    "24" => array("maqh"=>"034","name"=>"Huyện Bắc Quang","matp"=>"HAGIANG"),
    "25" => array("maqh"=>"035","name"=>"Huyện Quang Bình","matp"=>"HAGIANG"),
    "26" => array("maqh"=>"040","name"=>"Thành phố Cao Bằng","matp"=>"CAOBANG"),
    "27" => array("maqh"=>"042","name"=>"Huyện Bảo Lâm","matp"=>"CAOBANG"),
    "28" => array("maqh"=>"043","name"=>"Huyện Bảo Lạc","matp"=>"CAOBANG"),
    "29" => array("maqh"=>"045","name"=>"Huyện Hà Quảng","matp"=>"CAOBANG"),
    "30" => array("maqh"=>"047","name"=>"Huyện Trùng Khánh","matp"=>"CAOBANG"),
    "31" => array("maqh"=>"048","name"=>"Huyện Hạ Lang","matp"=>"CAOBANG"),
    "32" => array("maqh"=>"049","name"=>"Huyện Quảng Hòa","matp"=>"CAOBANG"),
    "33" => array("maqh"=>"051","name"=>"Huyện Hoà An","matp"=>"CAOBANG"),
    "34" => array("maqh"=>"052","name"=>"Huyện Nguyên Bình","matp"=>"CAOBANG"),
    "35" => array("maqh"=>"053","name"=>"Huyện Thạch An","matp"=>"CAOBANG"),
    "36" => array("maqh"=>"058","name"=>"Thành Phố Bắc Kạn","matp"=>"BACKAN"),
    "37" => array("maqh"=>"060","name"=>"Huyện Pác Nặm","matp"=>"BACKAN"),
    "38" => array("maqh"=>"061","name"=>"Huyện Ba Bể","matp"=>"BACKAN"),
    "39" => array("maqh"=>"062","name"=>"Huyện Ngân Sơn","matp"=>"BACKAN"),
    "40" => array("maqh"=>"063","name"=>"Huyện Bạch Thông","matp"=>"BACKAN"),
    "41" => array("maqh"=>"064","name"=>"Huyện Chợ Đồn","matp"=>"BACKAN"),
    "42" => array("maqh"=>"065","name"=>"Huyện Chợ Mới","matp"=>"BACKAN"),
    "43" => array("maqh"=>"066","name"=>"Huyện Na Rì","matp"=>"BACKAN"),
    "44" => array("maqh"=>"070","name"=>"Thành phố Tuyên Quang","matp"=>"TUYENQUANG"),
    "45" => array("maqh"=>"071","name"=>"Huyện Lâm Bình","matp"=>"TUYENQUANG"),
    "46" => array("maqh"=>"072","name"=>"Huyện Na Hang","matp"=>"TUYENQUANG"),
    "47" => array("maqh"=>"073","name"=>"Huyện Chiêm Hóa","matp"=>"TUYENQUANG"),
    "48" => array("maqh"=>"074","name"=>"Huyện Hàm Yên","matp"=>"TUYENQUANG"),
    "49" => array("maqh"=>"075","name"=>"Huyện Yên Sơn","matp"=>"TUYENQUANG"),
    "50" => array("maqh"=>"076","name"=>"Huyện Sơn Dương","matp"=>"TUYENQUANG"),
    "51" => array("maqh"=>"080","name"=>"Thành phố Lào Cai","matp"=>"LAOCAI"),
    "52" => array("maqh"=>"082","name"=>"Huyện Bát Xát","matp"=>"LAOCAI"),
    "53" => array("maqh"=>"083","name"=>"Huyện Mường Khương","matp"=>"LAOCAI"),
    "54" => array("maqh"=>"084","name"=>"Huyện Si Ma Cai","matp"=>"LAOCAI"),
    "55" => array("maqh"=>"085","name"=>"Huyện Bắc Hà","matp"=>"LAOCAI"),
    "56" => array("maqh"=>"086","name"=>"Huyện Bảo Thắng","matp"=>"LAOCAI"),
    "57" => array("maqh"=>"087","name"=>"Huyện Bảo Yên","matp"=>"LAOCAI"),
    "58" => array("maqh"=>"088","name"=>"Thị xã Sa Pa","matp"=>"LAOCAI"),
    "59" => array("maqh"=>"089","name"=>"Huyện Văn Bàn","matp"=>"LAOCAI"),
    "60" => array("maqh"=>"094","name"=>"Thành phố Điện Biên Phủ","matp"=>"DIENBIEN"),
    "61" => array("maqh"=>"095","name"=>"Thị Xã Mường Lay","matp"=>"DIENBIEN"),
    "62" => array("maqh"=>"096","name"=>"Huyện Mường Nhé","matp"=>"DIENBIEN"),
    "63" => array("maqh"=>"097","name"=>"Huyện Mường Chà","matp"=>"DIENBIEN"),
    "64" => array("maqh"=>"098","name"=>"Huyện Tủa Chùa","matp"=>"DIENBIEN"),
    "65" => array("maqh"=>"099","name"=>"Huyện Tuần Giáo","matp"=>"DIENBIEN"),
    "66" => array("maqh"=>"100","name"=>"Huyện Điện Biên","matp"=>"DIENBIEN"),
    "67" => array("maqh"=>"101","name"=>"Huyện Điện Biên Đông","matp"=>"DIENBIEN"),
    "68" => array("maqh"=>"102","name"=>"Huyện Mường Ảng","matp"=>"DIENBIEN"),
    "69" => array("maqh"=>"103","name"=>"Huyện Nậm Pồ","matp"=>"DIENBIEN"),
    "70" => array("maqh"=>"105","name"=>"Thành phố Lai Châu","matp"=>"LAICHAU"),
    "71" => array("maqh"=>"106","name"=>"Huyện Tam Đường","matp"=>"LAICHAU"),
    "72" => array("maqh"=>"107","name"=>"Huyện Mường Tè","matp"=>"LAICHAU"),
    "73" => array("maqh"=>"108","name"=>"Huyện Sìn Hồ","matp"=>"LAICHAU"),
    "74" => array("maqh"=>"109","name"=>"Huyện Phong Thổ","matp"=>"LAICHAU"),
    "75" => array("maqh"=>"110","name"=>"Huyện Than Uyên","matp"=>"LAICHAU"),
    "76" => array("maqh"=>"111","name"=>"Huyện Tân Uyên","matp"=>"LAICHAU"),
    "77" => array("maqh"=>"112","name"=>"Huyện Nậm Nhùn","matp"=>"LAICHAU"),
    "78" => array("maqh"=>"116","name"=>"Thành phố Sơn La","matp"=>"SONLA"),
    "79" => array("maqh"=>"118","name"=>"Huyện Quỳnh Nhai","matp"=>"SONLA"),
    "80" => array("maqh"=>"119","name"=>"Huyện Thuận Châu","matp"=>"SONLA"),
    "81" => array("maqh"=>"120","name"=>"Huyện Mường La","matp"=>"SONLA"),
    "82" => array("maqh"=>"121","name"=>"Huyện Bắc Yên","matp"=>"SONLA"),
    "83" => array("maqh"=>"122","name"=>"Huyện Phù Yên","matp"=>"SONLA"),
    "84" => array("maqh"=>"123","name"=>"Huyện Mộc Châu","matp"=>"SONLA"),
    "85" => array("maqh"=>"124","name"=>"Huyện Yên Châu","matp"=>"SONLA"),
    "86" => array("maqh"=>"125","name"=>"Huyện Mai Sơn","matp"=>"SONLA"),
    "87" => array("maqh"=>"126","name"=>"Huyện Sông Mã","matp"=>"SONLA"),
    "88" => array("maqh"=>"127","name"=>"Huyện Sốp Cộp","matp"=>"SONLA"),
    "89" => array("maqh"=>"128","name"=>"Huyện Vân Hồ","matp"=>"SONLA"),
    "90" => array("maqh"=>"132","name"=>"Thành phố Yên Bái","matp"=>"YENBAI"),
    "91" => array("maqh"=>"133","name"=>"Thị xã Nghĩa Lộ","matp"=>"YENBAI"),
    "92" => array("maqh"=>"135","name"=>"Huyện Lục Yên","matp"=>"YENBAI"),
    "93" => array("maqh"=>"136","name"=>"Huyện Văn Yên","matp"=>"YENBAI"),
    "94" => array("maqh"=>"137","name"=>"Huyện Mù Căng Chải","matp"=>"YENBAI"),
    "95" => array("maqh"=>"138","name"=>"Huyện Trấn Yên","matp"=>"YENBAI"),
    "96" => array("maqh"=>"139","name"=>"Huyện Trạm Tấu","matp"=>"YENBAI"),
    "97" => array("maqh"=>"140","name"=>"Huyện Văn Chấn","matp"=>"YENBAI"),
    "98" => array("maqh"=>"141","name"=>"Huyện Yên Bình","matp"=>"YENBAI"),
    "99" => array("maqh"=>"148","name"=>"Thành phố Hòa Bình","matp"=>"HOABINH"),
    "100" => array("maqh"=>"150","name"=>"Huyện Đà Bắc","matp"=>"HOABINH"),
    "101" => array("maqh"=>"152","name"=>"Huyện Lương Sơn","matp"=>"HOABINH"),
    "102" => array("maqh"=>"153","name"=>"Huyện Kim Bôi","matp"=>"HOABINH"),
    "103" => array("maqh"=>"154","name"=>"Huyện Cao Phong","matp"=>"HOABINH"),
    "104" => array("maqh"=>"155","name"=>"Huyện Tân Lạc","matp"=>"HOABINH"),
    "105" => array("maqh"=>"156","name"=>"Huyện Mai Châu","matp"=>"HOABINH"),
    "106" => array("maqh"=>"157","name"=>"Huyện Lạc Sơn","matp"=>"HOABINH"),
    "107" => array("maqh"=>"158","name"=>"Huyện Yên Thủy","matp"=>"HOABINH"),
    "108" => array("maqh"=>"159","name"=>"Huyện Lạc Thủy","matp"=>"HOABINH"),
    "109" => array("maqh"=>"164","name"=>"Thành phố Thái Nguyên","matp"=>"THAINGUYEN"),
    "110" => array("maqh"=>"165","name"=>"Thành phố Sông Công","matp"=>"THAINGUYEN"),
    "111" => array("maqh"=>"167","name"=>"Huyện Định Hóa","matp"=>"THAINGUYEN"),
    "112" => array("maqh"=>"168","name"=>"Huyện Phú Lương","matp"=>"THAINGUYEN"),
    "113" => array("maqh"=>"169","name"=>"Huyện Đồng Hỷ","matp"=>"THAINGUYEN"),
    "114" => array("maqh"=>"170","name"=>"Huyện Võ Nhai","matp"=>"THAINGUYEN"),
    "115" => array("maqh"=>"171","name"=>"Huyện Đại Từ","matp"=>"THAINGUYEN"),
    "116" => array("maqh"=>"172","name"=>"Thị xã Phổ Yên","matp"=>"THAINGUYEN"),
    "117" => array("maqh"=>"173","name"=>"Huyện Phú Bình","matp"=>"THAINGUYEN"),
    "118" => array("maqh"=>"178","name"=>"Thành phố Lạng Sơn","matp"=>"LANGSON"),
    "119" => array("maqh"=>"180","name"=>"Huyện Tràng Định","matp"=>"LANGSON"),
    "120" => array("maqh"=>"181","name"=>"Huyện Bình Gia","matp"=>"LANGSON"),
    "121" => array("maqh"=>"182","name"=>"Huyện Văn Lãng","matp"=>"LANGSON"),
    "122" => array("maqh"=>"183","name"=>"Huyện Cao Lộc","matp"=>"LANGSON"),
    "123" => array("maqh"=>"184","name"=>"Huyện Văn Quan","matp"=>"LANGSON"),
    "124" => array("maqh"=>"185","name"=>"Huyện Bắc Sơn","matp"=>"LANGSON"),
    "125" => array("maqh"=>"186","name"=>"Huyện Hữu Lũng","matp"=>"LANGSON"),
    "126" => array("maqh"=>"187","name"=>"Huyện Chi Lăng","matp"=>"LANGSON"),
    "127" => array("maqh"=>"188","name"=>"Huyện Lộc Bình","matp"=>"LANGSON"),
    "128" => array("maqh"=>"189","name"=>"Huyện Đình Lập","matp"=>"LANGSON"),
    "129" => array("maqh"=>"193","name"=>"Thành phố Hạ Long","matp"=>"QUANGNINH"),
    "130" => array("maqh"=>"194","name"=>"Thành phố Móng Cái","matp"=>"QUANGNINH"),
    "131" => array("maqh"=>"195","name"=>"Thành phố Cẩm Phả","matp"=>"QUANGNINH"),
    "132" => array("maqh"=>"196","name"=>"Thành phố Uông Bí","matp"=>"QUANGNINH"),
    "133" => array("maqh"=>"198","name"=>"Huyện Bình Liêu","matp"=>"QUANGNINH"),
    "134" => array("maqh"=>"199","name"=>"Huyện Tiên Yên","matp"=>"QUANGNINH"),
    "135" => array("maqh"=>"200","name"=>"Huyện Đầm Hà","matp"=>"QUANGNINH"),
    "136" => array("maqh"=>"201","name"=>"Huyện Hải Hà","matp"=>"QUANGNINH"),
    "137" => array("maqh"=>"202","name"=>"Huyện Ba Chẽ","matp"=>"QUANGNINH"),
    "138" => array("maqh"=>"203","name"=>"Huyện Vân Đồn","matp"=>"QUANGNINH"),
    "139" => array("maqh"=>"205","name"=>"Thị xã Đông Triều","matp"=>"QUANGNINH"),
    "140" => array("maqh"=>"206","name"=>"Thị xã Quảng Yên","matp"=>"QUANGNINH"),
    "141" => array("maqh"=>"207","name"=>"Huyện Cô Tô","matp"=>"QUANGNINH"),
    "142" => array("maqh"=>"213","name"=>"Thành phố Bắc Giang","matp"=>"BACGIANG"),
    "143" => array("maqh"=>"215","name"=>"Huyện Yên Thế","matp"=>"BACGIANG"),
    "144" => array("maqh"=>"216","name"=>"Huyện Tân Yên","matp"=>"BACGIANG"),
    "145" => array("maqh"=>"217","name"=>"Huyện Lạng Giang","matp"=>"BACGIANG"),
    "146" => array("maqh"=>"218","name"=>"Huyện Lục Nam","matp"=>"BACGIANG"),
    "147" => array("maqh"=>"219","name"=>"Huyện Lục Ngạn","matp"=>"BACGIANG"),
    "148" => array("maqh"=>"220","name"=>"Huyện Sơn Động","matp"=>"BACGIANG"),
    "149" => array("maqh"=>"221","name"=>"Huyện Yên Dũng","matp"=>"BACGIANG"),
    "150" => array("maqh"=>"222","name"=>"Huyện Việt Yên","matp"=>"BACGIANG"),
    "151" => array("maqh"=>"223","name"=>"Huyện Hiệp Hòa","matp"=>"BACGIANG"),
    "152" => array("maqh"=>"227","name"=>"Thành phố Việt Trì","matp"=>"PHUTHO"),
    "153" => array("maqh"=>"228","name"=>"Thị xã Phú Thọ","matp"=>"PHUTHO"),
    "154" => array("maqh"=>"230","name"=>"Huyện Đoan Hùng","matp"=>"PHUTHO"),
    "155" => array("maqh"=>"231","name"=>"Huyện Hạ Hoà","matp"=>"PHUTHO"),
    "156" => array("maqh"=>"232","name"=>"Huyện Thanh Ba","matp"=>"PHUTHO"),
    "157" => array("maqh"=>"233","name"=>"Huyện Phù Ninh","matp"=>"PHUTHO"),
    "158" => array("maqh"=>"234","name"=>"Huyện Yên Lập","matp"=>"PHUTHO"),
    "159" => array("maqh"=>"235","name"=>"Huyện Cẩm Khê","matp"=>"PHUTHO"),
    "160" => array("maqh"=>"236","name"=>"Huyện Tam Nông","matp"=>"PHUTHO"),
    "161" => array("maqh"=>"237","name"=>"Huyện Lâm Thao","matp"=>"PHUTHO"),
    "162" => array("maqh"=>"238","name"=>"Huyện Thanh Sơn","matp"=>"PHUTHO"),
    "163" => array("maqh"=>"239","name"=>"Huyện Thanh Thuỷ","matp"=>"PHUTHO"),
    "164" => array("maqh"=>"240","name"=>"Huyện Tân Sơn","matp"=>"PHUTHO"),
    "165" => array("maqh"=>"243","name"=>"Thành phố Vĩnh Yên","matp"=>"VINHPHUC"),
    "166" => array("maqh"=>"244","name"=>"Thành phố Phúc Yên","matp"=>"VINHPHUC"),
    "167" => array("maqh"=>"246","name"=>"Huyện Lập Thạch","matp"=>"VINHPHUC"),
    "168" => array("maqh"=>"247","name"=>"Huyện Tam Dương","matp"=>"VINHPHUC"),
    "169" => array("maqh"=>"248","name"=>"Huyện Tam Đảo","matp"=>"VINHPHUC"),
    "170" => array("maqh"=>"249","name"=>"Huyện Bình Xuyên","matp"=>"VINHPHUC"),
    "171" => array("maqh"=>"250","name"=>"Huyện Mê Linh","matp"=>"HANOI"),
    "172" => array("maqh"=>"251","name"=>"Huyện Yên Lạc","matp"=>"VINHPHUC"),
    "173" => array("maqh"=>"252","name"=>"Huyện Vĩnh Tường","matp"=>"VINHPHUC"),
    "174" => array("maqh"=>"253","name"=>"Huyện Sông Lô","matp"=>"VINHPHUC"),
    "175" => array("maqh"=>"256","name"=>"Thành phố Bắc Ninh","matp"=>"BACNINH"),
    "176" => array("maqh"=>"258","name"=>"Huyện Yên Phong","matp"=>"BACNINH"),
    "177" => array("maqh"=>"259","name"=>"Huyện Quế Võ","matp"=>"BACNINH"),
    "178" => array("maqh"=>"260","name"=>"Huyện Tiên Du","matp"=>"BACNINH"),
    "179" => array("maqh"=>"261","name"=>"Thị xã Từ Sơn","matp"=>"BACNINH"),
    "180" => array("maqh"=>"262","name"=>"Huyện Thuận Thành","matp"=>"BACNINH"),
    "181" => array("maqh"=>"263","name"=>"Huyện Gia Bình","matp"=>"BACNINH"),
    "182" => array("maqh"=>"264","name"=>"Huyện Lương Tài","matp"=>"BACNINH"),
    "183" => array("maqh"=>"268","name"=>"Quận Hà Đông","matp"=>"HANOI"),
    "184" => array("maqh"=>"269","name"=>"Thị xã Sơn Tây","matp"=>"HANOI"),
    "185" => array("maqh"=>"271","name"=>"Huyện Ba Vì","matp"=>"HANOI"),
    "186" => array("maqh"=>"272","name"=>"Huyện Phúc Thọ","matp"=>"HANOI"),
    "187" => array("maqh"=>"273","name"=>"Huyện Đan Phượng","matp"=>"HANOI"),
    "188" => array("maqh"=>"274","name"=>"Huyện Hoài Đức","matp"=>"HANOI"),
    "189" => array("maqh"=>"275","name"=>"Huyện Quốc Oai","matp"=>"HANOI"),
    "190" => array("maqh"=>"276","name"=>"Huyện Thạch Thất","matp"=>"HANOI"),
    "191" => array("maqh"=>"277","name"=>"Huyện Chương Mỹ","matp"=>"HANOI"),
    "192" => array("maqh"=>"278","name"=>"Huyện Thanh Oai","matp"=>"HANOI"),
    "193" => array("maqh"=>"279","name"=>"Huyện Thường Tín","matp"=>"HANOI"),
    "194" => array("maqh"=>"280","name"=>"Huyện Phú Xuyên","matp"=>"HANOI"),
    "195" => array("maqh"=>"281","name"=>"Huyện Ứng Hòa","matp"=>"HANOI"),
    "196" => array("maqh"=>"282","name"=>"Huyện Mỹ Đức","matp"=>"HANOI"),
    "197" => array("maqh"=>"288","name"=>"Thành phố Hải Dương","matp"=>"HAIDUONG"),
    "198" => array("maqh"=>"290","name"=>"Thành phố Chí Linh","matp"=>"HAIDUONG"),
    "199" => array("maqh"=>"291","name"=>"Huyện Nam Sách","matp"=>"HAIDUONG"),
    "200" => array("maqh"=>"292","name"=>"Thị xã Kinh Môn","matp"=>"HAIDUONG"),
    "201" => array("maqh"=>"293","name"=>"Huyện Kim Thành","matp"=>"HAIDUONG"),
    "202" => array("maqh"=>"294","name"=>"Huyện Thanh Hà","matp"=>"HAIDUONG"),
    "203" => array("maqh"=>"295","name"=>"Huyện Cẩm Giàng","matp"=>"HAIDUONG"),
    "204" => array("maqh"=>"296","name"=>"Huyện Bình Giang","matp"=>"HAIDUONG"),
    "205" => array("maqh"=>"297","name"=>"Huyện Gia Lộc","matp"=>"HAIDUONG"),
    "206" => array("maqh"=>"298","name"=>"Huyện Tứ Kỳ","matp"=>"HAIDUONG"),
    "207" => array("maqh"=>"299","name"=>"Huyện Ninh Giang","matp"=>"HAIDUONG"),
    "208" => array("maqh"=>"300","name"=>"Huyện Thanh Miện","matp"=>"HAIDUONG"),
    "209" => array("maqh"=>"303","name"=>"Quận Hồng Bàng","matp"=>"HAIPHONG"),
    "210" => array("maqh"=>"304","name"=>"Quận Ngô Quyền","matp"=>"HAIPHONG"),
    "211" => array("maqh"=>"305","name"=>"Quận Lê Chân","matp"=>"HAIPHONG"),
    "212" => array("maqh"=>"306","name"=>"Quận Hải An","matp"=>"HAIPHONG"),
    "213" => array("maqh"=>"307","name"=>"Quận Kiến An","matp"=>"HAIPHONG"),
    "214" => array("maqh"=>"308","name"=>"Quận Đồ Sơn","matp"=>"HAIPHONG"),
    "215" => array("maqh"=>"309","name"=>"Quận Dương Kinh","matp"=>"HAIPHONG"),
    "216" => array("maqh"=>"311","name"=>"Huyện Thuỷ Nguyên","matp"=>"HAIPHONG"),
    "217" => array("maqh"=>"312","name"=>"Huyện An Dương","matp"=>"HAIPHONG"),
    "218" => array("maqh"=>"313","name"=>"Huyện An Lão","matp"=>"HAIPHONG"),
    "219" => array("maqh"=>"314","name"=>"Huyện Kiến Thuỵ","matp"=>"HAIPHONG"),
    "220" => array("maqh"=>"315","name"=>"Huyện Tiên Lãng","matp"=>"HAIPHONG"),
    "221" => array("maqh"=>"316","name"=>"Huyện Vĩnh Bảo","matp"=>"HAIPHONG"),
    "222" => array("maqh"=>"317","name"=>"Huyện Cát Hải","matp"=>"HAIPHONG"),
    "223" => array("maqh"=>"318","name"=>"Huyện Bạch Long Vĩ","matp"=>"HAIPHONG"),
    "224" => array("maqh"=>"323","name"=>"Thành phố Hưng Yên","matp"=>"HUNGYEN"),
    "225" => array("maqh"=>"325","name"=>"Huyện Văn Lâm","matp"=>"HUNGYEN"),
    "226" => array("maqh"=>"326","name"=>"Huyện Văn Giang","matp"=>"HUNGYEN"),
    "227" => array("maqh"=>"327","name"=>"Huyện Yên Mỹ","matp"=>"HUNGYEN"),
    "228" => array("maqh"=>"328","name"=>"Thị xã Mỹ Hào","matp"=>"HUNGYEN"),
    "229" => array("maqh"=>"329","name"=>"Huyện Ân Thi","matp"=>"HUNGYEN"),
    "230" => array("maqh"=>"330","name"=>"Huyện Khoái Châu","matp"=>"HUNGYEN"),
    "231" => array("maqh"=>"331","name"=>"Huyện Kim Động","matp"=>"HUNGYEN"),
    "232" => array("maqh"=>"332","name"=>"Huyện Tiên Lữ","matp"=>"HUNGYEN"),
    "233" => array("maqh"=>"333","name"=>"Huyện Phù Cừ","matp"=>"HUNGYEN"),
    "234" => array("maqh"=>"336","name"=>"Thành phố Thái Bình","matp"=>"THAIBINH"),
    "235" => array("maqh"=>"338","name"=>"Huyện Quỳnh Phụ","matp"=>"THAIBINH"),
    "236" => array("maqh"=>"339","name"=>"Huyện Hưng Hà","matp"=>"THAIBINH"),
    "237" => array("maqh"=>"340","name"=>"Huyện Đông Hưng","matp"=>"THAIBINH"),
    "238" => array("maqh"=>"341","name"=>"Huyện Thái Thụy","matp"=>"THAIBINH"),
    "239" => array("maqh"=>"342","name"=>"Huyện Tiền Hải","matp"=>"THAIBINH"),
    "240" => array("maqh"=>"343","name"=>"Huyện Kiến Xương","matp"=>"THAIBINH"),
    "241" => array("maqh"=>"344","name"=>"Huyện Vũ Thư","matp"=>"THAIBINH"),
    "242" => array("maqh"=>"347","name"=>"Thành phố Phủ Lý","matp"=>"HANAM"),
    "243" => array("maqh"=>"349","name"=>"Thị xã Duy Tiên","matp"=>"HANAM"),
    "244" => array("maqh"=>"350","name"=>"Huyện Kim Bảng","matp"=>"HANAM"),
    "245" => array("maqh"=>"351","name"=>"Huyện Thanh Liêm","matp"=>"HANAM"),
    "246" => array("maqh"=>"352","name"=>"Huyện Bình Lục","matp"=>"HANAM"),
    "247" => array("maqh"=>"353","name"=>"Huyện Lý Nhân","matp"=>"HANAM"),
    "248" => array("maqh"=>"356","name"=>"Thành phố Nam Định","matp"=>"NAMDINH"),
    "249" => array("maqh"=>"358","name"=>"Huyện Mỹ Lộc","matp"=>"NAMDINH"),
    "250" => array("maqh"=>"359","name"=>"Huyện Vụ Bản","matp"=>"NAMDINH"),
    "251" => array("maqh"=>"360","name"=>"Huyện Ý Yên","matp"=>"NAMDINH"),
    "252" => array("maqh"=>"361","name"=>"Huyện Nghĩa Hưng","matp"=>"NAMDINH"),
    "253" => array("maqh"=>"362","name"=>"Huyện Nam Trực","matp"=>"NAMDINH"),
    "254" => array("maqh"=>"363","name"=>"Huyện Trực Ninh","matp"=>"NAMDINH"),
    "255" => array("maqh"=>"364","name"=>"Huyện Xuân Trường","matp"=>"NAMDINH"),
    "256" => array("maqh"=>"365","name"=>"Huyện Giao Thủy","matp"=>"NAMDINH"),
    "257" => array("maqh"=>"366","name"=>"Huyện Hải Hậu","matp"=>"NAMDINH"),
    "258" => array("maqh"=>"369","name"=>"Thành phố Ninh Bình","matp"=>"NINHBINH"),
    "259" => array("maqh"=>"370","name"=>"Thành phố Tam Điệp","matp"=>"NINHBINH"),
    "260" => array("maqh"=>"372","name"=>"Huyện Nho Quan","matp"=>"NINHBINH"),
    "261" => array("maqh"=>"373","name"=>"Huyện Gia Viễn","matp"=>"NINHBINH"),
    "262" => array("maqh"=>"374","name"=>"Huyện Hoa Lư","matp"=>"NINHBINH"),
    "263" => array("maqh"=>"375","name"=>"Huyện Yên Khánh","matp"=>"NINHBINH"),
    "264" => array("maqh"=>"376","name"=>"Huyện Kim Sơn","matp"=>"NINHBINH"),
    "265" => array("maqh"=>"377","name"=>"Huyện Yên Mô","matp"=>"NINHBINH"),
    "266" => array("maqh"=>"380","name"=>"Thành phố Thanh Hóa","matp"=>"THANHHOA"),
    "267" => array("maqh"=>"381","name"=>"Thị xã Bỉm Sơn","matp"=>"THANHHOA"),
    "268" => array("maqh"=>"382","name"=>"Thành phố Sầm Sơn","matp"=>"THANHHOA"),
    "269" => array("maqh"=>"384","name"=>"Huyện Mường Lát","matp"=>"THANHHOA"),
    "270" => array("maqh"=>"385","name"=>"Huyện Quan Hóa","matp"=>"THANHHOA"),
    "271" => array("maqh"=>"386","name"=>"Huyện Bá Thước","matp"=>"THANHHOA"),
    "272" => array("maqh"=>"387","name"=>"Huyện Quan Sơn","matp"=>"THANHHOA"),
    "273" => array("maqh"=>"388","name"=>"Huyện Lang Chánh","matp"=>"THANHHOA"),
    "274" => array("maqh"=>"389","name"=>"Huyện Ngọc Lặc","matp"=>"THANHHOA"),
    "275" => array("maqh"=>"390","name"=>"Huyện Cẩm Thủy","matp"=>"THANHHOA"),
    "276" => array("maqh"=>"391","name"=>"Huyện Thạch Thành","matp"=>"THANHHOA"),
    "277" => array("maqh"=>"392","name"=>"Huyện Hà Trung","matp"=>"THANHHOA"),
    "278" => array("maqh"=>"393","name"=>"Huyện Vĩnh Lộc","matp"=>"THANHHOA"),
    "279" => array("maqh"=>"394","name"=>"Huyện Yên Định","matp"=>"THANHHOA"),
    "280" => array("maqh"=>"395","name"=>"Huyện Thọ Xuân","matp"=>"THANHHOA"),
    "281" => array("maqh"=>"396","name"=>"Huyện Thường Xuân","matp"=>"THANHHOA"),
    "282" => array("maqh"=>"397","name"=>"Huyện Triệu Sơn","matp"=>"THANHHOA"),
    "283" => array("maqh"=>"398","name"=>"Huyện Thiệu Hóa","matp"=>"THANHHOA"),
    "284" => array("maqh"=>"399","name"=>"Huyện Hoằng Hóa","matp"=>"THANHHOA"),
    "285" => array("maqh"=>"400","name"=>"Huyện Hậu Lộc","matp"=>"THANHHOA"),
    "286" => array("maqh"=>"401","name"=>"Huyện Nga Sơn","matp"=>"THANHHOA"),
    "287" => array("maqh"=>"402","name"=>"Huyện Như Xuân","matp"=>"THANHHOA"),
    "288" => array("maqh"=>"403","name"=>"Huyện Như Thanh","matp"=>"THANHHOA"),
    "289" => array("maqh"=>"404","name"=>"Huyện Nông Cống","matp"=>"THANHHOA"),
    "290" => array("maqh"=>"405","name"=>"Huyện Đông Sơn","matp"=>"THANHHOA"),
    "291" => array("maqh"=>"406","name"=>"Huyện Quảng Xương","matp"=>"THANHHOA"),
    "292" => array("maqh"=>"407","name"=>"Thị xã Nghi Sơn","matp"=>"THANHHOA"),
    "293" => array("maqh"=>"412","name"=>"Thành phố Vinh","matp"=>"NGHEAN"),
    "294" => array("maqh"=>"413","name"=>"Thị xã Cửa Lò","matp"=>"NGHEAN"),
    "295" => array("maqh"=>"414","name"=>"Thị xã Thái Hoà","matp"=>"NGHEAN"),
    "296" => array("maqh"=>"415","name"=>"Huyện Quế Phong","matp"=>"NGHEAN"),
    "297" => array("maqh"=>"416","name"=>"Huyện Quỳ Châu","matp"=>"NGHEAN"),
    "298" => array("maqh"=>"417","name"=>"Huyện Kỳ Sơn","matp"=>"NGHEAN"),
    "299" => array("maqh"=>"418","name"=>"Huyện Tương Dương","matp"=>"NGHEAN"),
    "300" => array("maqh"=>"419","name"=>"Huyện Nghĩa Đàn","matp"=>"NGHEAN"),
    "301" => array("maqh"=>"420","name"=>"Huyện Quỳ Hợp","matp"=>"NGHEAN"),
    "302" => array("maqh"=>"421","name"=>"Huyện Quỳnh Lưu","matp"=>"NGHEAN"),
    "303" => array("maqh"=>"422","name"=>"Huyện Con Cuông","matp"=>"NGHEAN"),
    "304" => array("maqh"=>"423","name"=>"Huyện Tân Kỳ","matp"=>"NGHEAN"),
    "305" => array("maqh"=>"424","name"=>"Huyện Anh Sơn","matp"=>"NGHEAN"),
    "306" => array("maqh"=>"425","name"=>"Huyện Diễn Châu","matp"=>"NGHEAN"),
    "307" => array("maqh"=>"426","name"=>"Huyện Yên Thành","matp"=>"NGHEAN"),
    "308" => array("maqh"=>"427","name"=>"Huyện Đô Lương","matp"=>"NGHEAN"),
    "309" => array("maqh"=>"428","name"=>"Huyện Thanh Chương","matp"=>"NGHEAN"),
    "310" => array("maqh"=>"429","name"=>"Huyện Nghi Lộc","matp"=>"NGHEAN"),
    "311" => array("maqh"=>"430","name"=>"Huyện Nam Đàn","matp"=>"NGHEAN"),
    "312" => array("maqh"=>"431","name"=>"Huyện Hưng Nguyên","matp"=>"NGHEAN"),
    "313" => array("maqh"=>"432","name"=>"Thị xã Hoàng Mai","matp"=>"NGHEAN"),
    "314" => array("maqh"=>"436","name"=>"Thành phố Hà Tĩnh","matp"=>"HATINH"),
    "315" => array("maqh"=>"437","name"=>"Thị xã Hồng Lĩnh","matp"=>"HATINH"),
    "316" => array("maqh"=>"439","name"=>"Huyện Hương Sơn","matp"=>"HATINH"),
    "317" => array("maqh"=>"440","name"=>"Huyện Đức Thọ","matp"=>"HATINH"),
    "318" => array("maqh"=>"441","name"=>"Huyện Vũ Quang","matp"=>"HATINH"),
    "319" => array("maqh"=>"442","name"=>"Huyện Nghi Xuân","matp"=>"HATINH"),
    "320" => array("maqh"=>"443","name"=>"Huyện Can Lộc","matp"=>"HATINH"),
    "321" => array("maqh"=>"444","name"=>"Huyện Hương Khê","matp"=>"HATINH"),
    "322" => array("maqh"=>"445","name"=>"Huyện Thạch Hà","matp"=>"HATINH"),
    "323" => array("maqh"=>"446","name"=>"Huyện Cẩm Xuyên","matp"=>"HATINH"),
    "324" => array("maqh"=>"447","name"=>"Huyện Kỳ Anh","matp"=>"HATINH"),
    "325" => array("maqh"=>"448","name"=>"Huyện Lộc Hà","matp"=>"HATINH"),
    "326" => array("maqh"=>"449","name"=>"Thị xã Kỳ Anh","matp"=>"HATINH"),
    "327" => array("maqh"=>"450","name"=>"Thành Phố Đồng Hới","matp"=>"QUANGBINH"),
    "328" => array("maqh"=>"452","name"=>"Huyện Minh Hóa","matp"=>"QUANGBINH"),
    "329" => array("maqh"=>"453","name"=>"Huyện Tuyên Hóa","matp"=>"QUANGBINH"),
    "330" => array("maqh"=>"454","name"=>"Huyện Quảng Trạch","matp"=>"QUANGBINH"),
    "331" => array("maqh"=>"455","name"=>"Huyện Bố Trạch","matp"=>"QUANGBINH"),
    "332" => array("maqh"=>"456","name"=>"Huyện Quảng Ninh","matp"=>"QUANGBINH"),
    "333" => array("maqh"=>"457","name"=>"Huyện Lệ Thủy","matp"=>"QUANGBINH"),
    "334" => array("maqh"=>"458","name"=>"Thị xã Ba Đồn","matp"=>"QUANGBINH"),
    "335" => array("maqh"=>"461","name"=>"Thành phố Đông Hà","matp"=>"QUANGTRI"),
    "336" => array("maqh"=>"462","name"=>"Thị xã Quảng Trị","matp"=>"QUANGTRI"),
    "337" => array("maqh"=>"464","name"=>"Huyện Vĩnh Linh","matp"=>"QUANGTRI"),
    "338" => array("maqh"=>"465","name"=>"Huyện Hướng Hóa","matp"=>"QUANGTRI"),
    "339" => array("maqh"=>"466","name"=>"Huyện Gio Linh","matp"=>"QUANGTRI"),
    "340" => array("maqh"=>"467","name"=>"Huyện Đa Krông","matp"=>"QUANGTRI"),
    "341" => array("maqh"=>"468","name"=>"Huyện Cam Lộ","matp"=>"QUANGTRI"),
    "342" => array("maqh"=>"469","name"=>"Huyện Triệu Phong","matp"=>"QUANGTRI"),
    "343" => array("maqh"=>"470","name"=>"Huyện Hải Lăng","matp"=>"QUANGTRI"),
    "344" => array("maqh"=>"471","name"=>"Huyện Cồn Cỏ","matp"=>"QUANGTRI"),
    "345" => array("maqh"=>"474","name"=>"Thành phố Huế","matp"=>"THUATHIENHUE"),
    "346" => array("maqh"=>"476","name"=>"Huyện Phong Điền","matp"=>"THUATHIENHUE"),
    "347" => array("maqh"=>"477","name"=>"Huyện Quảng Điền","matp"=>"THUATHIENHUE"),
    "348" => array("maqh"=>"478","name"=>"Huyện Phú Vang","matp"=>"THUATHIENHUE"),
    "349" => array("maqh"=>"479","name"=>"Thị xã Hương Thủy","matp"=>"THUATHIENHUE"),
    "350" => array("maqh"=>"480","name"=>"Thị xã Hương Trà","matp"=>"THUATHIENHUE"),
    "351" => array("maqh"=>"481","name"=>"Huyện A Lưới","matp"=>"THUATHIENHUE"),
    "352" => array("maqh"=>"482","name"=>"Huyện Phú Lộc","matp"=>"THUATHIENHUE"),
    "353" => array("maqh"=>"483","name"=>"Huyện Nam Đông","matp"=>"THUATHIENHUE"),
    "354" => array("maqh"=>"490","name"=>"Quận Liên Chiểu","matp"=>"DANANG"),
    "355" => array("maqh"=>"491","name"=>"Quận Thanh Khê","matp"=>"DANANG"),
    "356" => array("maqh"=>"492","name"=>"Quận Hải Châu","matp"=>"DANANG"),
    "357" => array("maqh"=>"493","name"=>"Quận Sơn Trà","matp"=>"DANANG"),
    "358" => array("maqh"=>"494","name"=>"Quận Ngũ Hành Sơn","matp"=>"DANANG"),
    "359" => array("maqh"=>"495","name"=>"Quận Cẩm Lệ","matp"=>"DANANG"),
    "360" => array("maqh"=>"497","name"=>"Huyện Hòa Vang","matp"=>"DANANG"),
    "361" => array("maqh"=>"498","name"=>"Huyện Hoàng Sa","matp"=>"DANANG"),
    "362" => array("maqh"=>"502","name"=>"Thành phố Tam Kỳ","matp"=>"QUANGNAM"),
    "363" => array("maqh"=>"503","name"=>"Thành phố Hội An","matp"=>"QUANGNAM"),
    "364" => array("maqh"=>"504","name"=>"Huyện Tây Giang","matp"=>"QUANGNAM"),
    "365" => array("maqh"=>"505","name"=>"Huyện Đông Giang","matp"=>"QUANGNAM"),
    "366" => array("maqh"=>"506","name"=>"Huyện Đại Lộc","matp"=>"QUANGNAM"),
    "367" => array("maqh"=>"507","name"=>"Thị xã Điện Bàn","matp"=>"QUANGNAM"),
    "368" => array("maqh"=>"508","name"=>"Huyện Duy Xuyên","matp"=>"QUANGNAM"),
    "369" => array("maqh"=>"509","name"=>"Huyện Quế Sơn","matp"=>"QUANGNAM"),
    "370" => array("maqh"=>"510","name"=>"Huyện Nam Giang","matp"=>"QUANGNAM"),
    "371" => array("maqh"=>"511","name"=>"Huyện Phước Sơn","matp"=>"QUANGNAM"),
    "372" => array("maqh"=>"512","name"=>"Huyện Hiệp Đức","matp"=>"QUANGNAM"),
    "373" => array("maqh"=>"513","name"=>"Huyện Thăng Bình","matp"=>"QUANGNAM"),
    "374" => array("maqh"=>"514","name"=>"Huyện Tiên Phước","matp"=>"QUANGNAM"),
    "375" => array("maqh"=>"515","name"=>"Huyện Bắc Trà My","matp"=>"QUANGNAM"),
    "376" => array("maqh"=>"516","name"=>"Huyện Nam Trà My","matp"=>"QUANGNAM"),
    "377" => array("maqh"=>"517","name"=>"Huyện Núi Thành","matp"=>"QUANGNAM"),
    "378" => array("maqh"=>"518","name"=>"Huyện Phú Ninh","matp"=>"QUANGNAM"),
    "379" => array("maqh"=>"519","name"=>"Huyện Nông Sơn","matp"=>"QUANGNAM"),
    "380" => array("maqh"=>"522","name"=>"Thành phố Quảng Ngãi","matp"=>"QUANGNGAI"),
    "381" => array("maqh"=>"524","name"=>"Huyện Bình Sơn","matp"=>"QUANGNGAI"),
    "382" => array("maqh"=>"525","name"=>"Huyện Trà Bồng","matp"=>"QUANGNGAI"),
    "383" => array("maqh"=>"527","name"=>"Huyện Sơn Tịnh","matp"=>"QUANGNGAI"),
    "384" => array("maqh"=>"528","name"=>"Huyện Tư Nghĩa","matp"=>"QUANGNGAI"),
    "385" => array("maqh"=>"529","name"=>"Huyện Sơn Hà","matp"=>"QUANGNGAI"),
    "386" => array("maqh"=>"530","name"=>"Huyện Sơn Tây","matp"=>"QUANGNGAI"),
    "387" => array("maqh"=>"531","name"=>"Huyện Minh Long","matp"=>"QUANGNGAI"),
    "388" => array("maqh"=>"532","name"=>"Huyện Nghĩa Hành","matp"=>"QUANGNGAI"),
    "389" => array("maqh"=>"533","name"=>"Huyện Mộ Đức","matp"=>"QUANGNGAI"),
    "390" => array("maqh"=>"534","name"=>"Thị xã Đức Phổ","matp"=>"QUANGNGAI"),
    "391" => array("maqh"=>"535","name"=>"Huyện Ba Tơ","matp"=>"QUANGNGAI"),
    "392" => array("maqh"=>"536","name"=>"Huyện Lý Sơn","matp"=>"QUANGNGAI"),
    "393" => array("maqh"=>"540","name"=>"Thành phố Quy Nhơn","matp"=>"BINHDINH"),
    "394" => array("maqh"=>"542","name"=>"Huyện An Lão","matp"=>"BINHDINH"),
    "395" => array("maqh"=>"543","name"=>"Thị xã Hoài Nhơn","matp"=>"BINHDINH"),
    "396" => array("maqh"=>"544","name"=>"Huyện Hoài Ân","matp"=>"BINHDINH"),
    "397" => array("maqh"=>"545","name"=>"Huyện Phù Mỹ","matp"=>"BINHDINH"),
    "398" => array("maqh"=>"546","name"=>"Huyện Vĩnh Thạnh","matp"=>"BINHDINH"),
    "399" => array("maqh"=>"547","name"=>"Huyện Tây Sơn","matp"=>"BINHDINH"),
    "400" => array("maqh"=>"548","name"=>"Huyện Phù Cát","matp"=>"BINHDINH"),
    "401" => array("maqh"=>"549","name"=>"Thị xã An Nhơn","matp"=>"BINHDINH"),
    "402" => array("maqh"=>"550","name"=>"Huyện Tuy Phước","matp"=>"BINHDINH"),
    "403" => array("maqh"=>"551","name"=>"Huyện Vân Canh","matp"=>"BINHDINH"),
    "404" => array("maqh"=>"555","name"=>"Thành phố Tuy Hoà","matp"=>"PHUYEN"),
    "405" => array("maqh"=>"557","name"=>"Thị xã Sông Cầu","matp"=>"PHUYEN"),
    "406" => array("maqh"=>"558","name"=>"Huyện Đồng Xuân","matp"=>"PHUYEN"),
    "407" => array("maqh"=>"559","name"=>"Huyện Tuy An","matp"=>"PHUYEN"),
    "408" => array("maqh"=>"560","name"=>"Huyện Sơn Hòa","matp"=>"PHUYEN"),
    "409" => array("maqh"=>"561","name"=>"Huyện Sông Hinh","matp"=>"PHUYEN"),
    "410" => array("maqh"=>"562","name"=>"Huyện Tây Hoà","matp"=>"PHUYEN"),
    "411" => array("maqh"=>"563","name"=>"Huyện Phú Hoà","matp"=>"PHUYEN"),
    "412" => array("maqh"=>"564","name"=>"Thị xã Đông Hòa","matp"=>"PHUYEN"),
    "413" => array("maqh"=>"568","name"=>"Thành phố Nha Trang","matp"=>"KHANHHOA"),
    "414" => array("maqh"=>"569","name"=>"Thành phố Cam Ranh","matp"=>"KHANHHOA"),
    "415" => array("maqh"=>"570","name"=>"Huyện Cam Lâm","matp"=>"KHANHHOA"),
    "416" => array("maqh"=>"571","name"=>"Huyện Vạn Ninh","matp"=>"KHANHHOA"),
    "417" => array("maqh"=>"572","name"=>"Thị xã Ninh Hòa","matp"=>"KHANHHOA"),
    "418" => array("maqh"=>"573","name"=>"Huyện Khánh Vĩnh","matp"=>"KHANHHOA"),
    "419" => array("maqh"=>"574","name"=>"Huyện Diên Khánh","matp"=>"KHANHHOA"),
    "420" => array("maqh"=>"575","name"=>"Huyện Khánh Sơn","matp"=>"KHANHHOA"),
    "421" => array("maqh"=>"576","name"=>"Huyện Trường Sa","matp"=>"KHANHHOA"),
    "422" => array("maqh"=>"582","name"=>"Thành phố Phan Rang-Tháp Chàm","matp"=>"NINHTHUAN"),
    "423" => array("maqh"=>"584","name"=>"Huyện Bác Ái","matp"=>"NINHTHUAN"),
    "424" => array("maqh"=>"585","name"=>"Huyện Ninh Sơn","matp"=>"NINHTHUAN"),
    "425" => array("maqh"=>"586","name"=>"Huyện Ninh Hải","matp"=>"NINHTHUAN"),
    "426" => array("maqh"=>"587","name"=>"Huyện Ninh Phước","matp"=>"NINHTHUAN"),
    "427" => array("maqh"=>"588","name"=>"Huyện Thuận Bắc","matp"=>"NINHTHUAN"),
    "428" => array("maqh"=>"589","name"=>"Huyện Thuận Nam","matp"=>"NINHTHUAN"),
    "429" => array("maqh"=>"593","name"=>"Thành phố Phan Thiết","matp"=>"BINHTHUAN"),
    "430" => array("maqh"=>"594","name"=>"Thị xã La Gi","matp"=>"BINHTHUAN"),
    "431" => array("maqh"=>"595","name"=>"Huyện Tuy Phong","matp"=>"BINHTHUAN"),
    "432" => array("maqh"=>"596","name"=>"Huyện Bắc Bình","matp"=>"BINHTHUAN"),
    "433" => array("maqh"=>"597","name"=>"Huyện Hàm Thuận Bắc","matp"=>"BINHTHUAN"),
    "434" => array("maqh"=>"598","name"=>"Huyện Hàm Thuận Nam","matp"=>"BINHTHUAN"),
    "435" => array("maqh"=>"599","name"=>"Huyện Tánh Linh","matp"=>"BINHTHUAN"),
    "436" => array("maqh"=>"600","name"=>"Huyện Đức Linh","matp"=>"BINHTHUAN"),
    "437" => array("maqh"=>"601","name"=>"Huyện Hàm Tân","matp"=>"BINHTHUAN"),
    "438" => array("maqh"=>"602","name"=>"Huyện Phú Quí","matp"=>"BINHTHUAN"),
    "439" => array("maqh"=>"608","name"=>"Thành phố Kon Tum","matp"=>"KONTUM"),
    "440" => array("maqh"=>"610","name"=>"Huyện Đắk Glei","matp"=>"KONTUM"),
    "441" => array("maqh"=>"611","name"=>"Huyện Ngọc Hồi","matp"=>"KONTUM"),
    "442" => array("maqh"=>"612","name"=>"Huyện Đắk Tô","matp"=>"KONTUM"),
    "443" => array("maqh"=>"613","name"=>"Huyện Kon Plông","matp"=>"KONTUM"),
    "444" => array("maqh"=>"614","name"=>"Huyện Kon Rẫy","matp"=>"KONTUM"),
    "445" => array("maqh"=>"615","name"=>"Huyện Đắk Hà","matp"=>"KONTUM"),
    "446" => array("maqh"=>"616","name"=>"Huyện Sa Thầy","matp"=>"KONTUM"),
    "447" => array("maqh"=>"617","name"=>"Huyện Tu Mơ Rông","matp"=>"KONTUM"),
    "448" => array("maqh"=>"618","name"=>"Huyện Ia H' Drai","matp"=>"KONTUM"),
    "449" => array("maqh"=>"622","name"=>"Thành phố Pleiku","matp"=>"GIALAI"),
    "450" => array("maqh"=>"623","name"=>"Thị xã An Khê","matp"=>"GIALAI"),
    "451" => array("maqh"=>"624","name"=>"Thị xã Ayun Pa","matp"=>"GIALAI"),
    "452" => array("maqh"=>"625","name"=>"Huyện KBang","matp"=>"GIALAI"),
    "453" => array("maqh"=>"626","name"=>"Huyện Đăk Đoa","matp"=>"GIALAI"),
    "454" => array("maqh"=>"627","name"=>"Huyện Chư Păh","matp"=>"GIALAI"),
    "455" => array("maqh"=>"628","name"=>"Huyện Ia Grai","matp"=>"GIALAI"),
    "456" => array("maqh"=>"629","name"=>"Huyện Mang Yang","matp"=>"GIALAI"),
    "457" => array("maqh"=>"630","name"=>"Huyện Kông Chro","matp"=>"GIALAI"),
    "458" => array("maqh"=>"631","name"=>"Huyện Đức Cơ","matp"=>"GIALAI"),
    "459" => array("maqh"=>"632","name"=>"Huyện Chư Prông","matp"=>"GIALAI"),
    "460" => array("maqh"=>"633","name"=>"Huyện Chư Sê","matp"=>"GIALAI"),
    "461" => array("maqh"=>"634","name"=>"Huyện Đăk Pơ","matp"=>"GIALAI"),
    "462" => array("maqh"=>"635","name"=>"Huyện Ia Pa","matp"=>"GIALAI"),
    "463" => array("maqh"=>"637","name"=>"Huyện Krông Pa","matp"=>"GIALAI"),
    "464" => array("maqh"=>"638","name"=>"Huyện Phú Thiện","matp"=>"GIALAI"),
    "465" => array("maqh"=>"639","name"=>"Huyện Chư Pưh","matp"=>"GIALAI"),
    "466" => array("maqh"=>"643","name"=>"Thành phố Buôn Ma Thuột","matp"=>"DAKLAK"),
    "467" => array("maqh"=>"644","name"=>"Thị Xã Buôn Hồ","matp"=>"DAKLAK"),
    "468" => array("maqh"=>"645","name"=>"Huyện Ea H'leo","matp"=>"DAKLAK"),
    "469" => array("maqh"=>"646","name"=>"Huyện Ea Súp","matp"=>"DAKLAK"),
    "470" => array("maqh"=>"647","name"=>"Huyện Buôn Đôn","matp"=>"DAKLAK"),
    "471" => array("maqh"=>"648","name"=>"Huyện Cư M'gar","matp"=>"DAKLAK"),
    "472" => array("maqh"=>"649","name"=>"Huyện Krông Búk","matp"=>"DAKLAK"),
    "473" => array("maqh"=>"650","name"=>"Huyện Krông Năng","matp"=>"DAKLAK"),
    "474" => array("maqh"=>"651","name"=>"Huyện Ea Kar","matp"=>"DAKLAK"),
    "475" => array("maqh"=>"652","name"=>"Huyện M'Đrắk","matp"=>"DAKLAK"),
    "476" => array("maqh"=>"653","name"=>"Huyện Krông Bông","matp"=>"DAKLAK"),
    "477" => array("maqh"=>"654","name"=>"Huyện Krông Pắc","matp"=>"DAKLAK"),
    "478" => array("maqh"=>"655","name"=>"Huyện Krông A Na","matp"=>"DAKLAK"),
    "479" => array("maqh"=>"656","name"=>"Huyện Lắk","matp"=>"DAKLAK"),
    "480" => array("maqh"=>"657","name"=>"Huyện Cư Kuin","matp"=>"DAKLAK"),
    "481" => array("maqh"=>"660","name"=>"Thành phố Gia Nghĩa","matp"=>"DAKNONG"),
    "482" => array("maqh"=>"661","name"=>"Huyện Đăk Glong","matp"=>"DAKNONG"),
    "483" => array("maqh"=>"662","name"=>"Huyện Cư Jút","matp"=>"DAKNONG"),
    "484" => array("maqh"=>"663","name"=>"Huyện Đắk Mil","matp"=>"DAKNONG"),
    "485" => array("maqh"=>"664","name"=>"Huyện Krông Nô","matp"=>"DAKNONG"),
    "486" => array("maqh"=>"665","name"=>"Huyện Đắk Song","matp"=>"DAKNONG"),
    "487" => array("maqh"=>"666","name"=>"Huyện Đắk R'Lấp","matp"=>"DAKNONG"),
    "488" => array("maqh"=>"667","name"=>"Huyện Tuy Đức","matp"=>"DAKNONG"),
    "489" => array("maqh"=>"672","name"=>"Thành phố Đà Lạt","matp"=>"LAMDONG"),
    "490" => array("maqh"=>"673","name"=>"Thành phố Bảo Lộc","matp"=>"LAMDONG"),
    "491" => array("maqh"=>"674","name"=>"Huyện Đam Rông","matp"=>"LAMDONG"),
    "492" => array("maqh"=>"675","name"=>"Huyện Lạc Dương","matp"=>"LAMDONG"),
    "493" => array("maqh"=>"676","name"=>"Huyện Lâm Hà","matp"=>"LAMDONG"),
    "494" => array("maqh"=>"677","name"=>"Huyện Đơn Dương","matp"=>"LAMDONG"),
    "495" => array("maqh"=>"678","name"=>"Huyện Đức Trọng","matp"=>"LAMDONG"),
    "496" => array("maqh"=>"679","name"=>"Huyện Di Linh","matp"=>"LAMDONG"),
    "497" => array("maqh"=>"680","name"=>"Huyện Bảo Lâm","matp"=>"LAMDONG"),
    "498" => array("maqh"=>"681","name"=>"Huyện Đạ Huoai","matp"=>"LAMDONG"),
    "499" => array("maqh"=>"682","name"=>"Huyện Đạ Tẻh","matp"=>"LAMDONG"),
    "500" => array("maqh"=>"683","name"=>"Huyện Cát Tiên","matp"=>"LAMDONG"),
    "501" => array("maqh"=>"688","name"=>"Thị xã Phước Long","matp"=>"BINHPHUOC"),
    "502" => array("maqh"=>"689","name"=>"Thành phố Đồng Xoài","matp"=>"BINHPHUOC"),
    "503" => array("maqh"=>"690","name"=>"Thị xã Bình Long","matp"=>"BINHPHUOC"),
    "504" => array("maqh"=>"691","name"=>"Huyện Bù Gia Mập","matp"=>"BINHPHUOC"),
    "505" => array("maqh"=>"692","name"=>"Huyện Lộc Ninh","matp"=>"BINHPHUOC"),
    "506" => array("maqh"=>"693","name"=>"Huyện Bù Đốp","matp"=>"BINHPHUOC"),
    "507" => array("maqh"=>"694","name"=>"Huyện Hớn Quản","matp"=>"BINHPHUOC"),
    "508" => array("maqh"=>"695","name"=>"Huyện Đồng Phú","matp"=>"BINHPHUOC"),
    "509" => array("maqh"=>"696","name"=>"Huyện Bù Đăng","matp"=>"BINHPHUOC"),
    "510" => array("maqh"=>"697","name"=>"Huyện Chơn Thành","matp"=>"BINHPHUOC"),
    "511" => array("maqh"=>"698","name"=>"Huyện Phú Riềng","matp"=>"BINHPHUOC"),
    "512" => array("maqh"=>"703","name"=>"Thành phố Tây Ninh","matp"=>"TAYNINH"),
    "513" => array("maqh"=>"705","name"=>"Huyện Tân Biên","matp"=>"TAYNINH"),
    "514" => array("maqh"=>"706","name"=>"Huyện Tân Châu","matp"=>"TAYNINH"),
    "515" => array("maqh"=>"707","name"=>"Huyện Dương Minh Châu","matp"=>"TAYNINH"),
    "516" => array("maqh"=>"708","name"=>"Huyện Châu Thành","matp"=>"TAYNINH"),
    "517" => array("maqh"=>"709","name"=>"Thị xã Hòa Thành","matp"=>"TAYNINH"),
    "518" => array("maqh"=>"710","name"=>"Huyện Gò Dầu","matp"=>"TAYNINH"),
    "519" => array("maqh"=>"711","name"=>"Huyện Bến Cầu","matp"=>"TAYNINH"),
    "520" => array("maqh"=>"712","name"=>"Thị xã Trảng Bàng","matp"=>"TAYNINH"),
    "521" => array("maqh"=>"718","name"=>"Thành phố Thủ Dầu Một","matp"=>"BINHDUONG"),
    "522" => array("maqh"=>"719","name"=>"Huyện Bàu Bàng","matp"=>"BINHDUONG"),
    "523" => array("maqh"=>"720","name"=>"Huyện Dầu Tiếng","matp"=>"BINHDUONG"),
    "524" => array("maqh"=>"721","name"=>"Thị xã Bến Cát","matp"=>"BINHDUONG"),
    "525" => array("maqh"=>"722","name"=>"Huyện Phú Giáo","matp"=>"BINHDUONG"),
    "526" => array("maqh"=>"723","name"=>"Thị xã Tân Uyên","matp"=>"BINHDUONG"),
    "527" => array("maqh"=>"724","name"=>"Thành phố Dĩ An","matp"=>"BINHDUONG"),
    "528" => array("maqh"=>"725","name"=>"Thành phố Thuận An","matp"=>"BINHDUONG"),
    "529" => array("maqh"=>"726","name"=>"Huyện Bắc Tân Uyên","matp"=>"BINHDUONG"),
    "530" => array("maqh"=>"731","name"=>"Thành phố Biên Hòa","matp"=>"DONGNAI"),
    "531" => array("maqh"=>"732","name"=>"Thành phố Long Khánh","matp"=>"DONGNAI"),
    "532" => array("maqh"=>"734","name"=>"Huyện Tân Phú","matp"=>"DONGNAI"),
    "533" => array("maqh"=>"735","name"=>"Huyện Vĩnh Cửu","matp"=>"DONGNAI"),
    "534" => array("maqh"=>"736","name"=>"Huyện Định Quán","matp"=>"DONGNAI"),
    "535" => array("maqh"=>"737","name"=>"Huyện Trảng Bom","matp"=>"DONGNAI"),
    "536" => array("maqh"=>"738","name"=>"Huyện Thống Nhất","matp"=>"DONGNAI"),
    "537" => array("maqh"=>"739","name"=>"Huyện Cẩm Mỹ","matp"=>"DONGNAI"),
    "538" => array("maqh"=>"740","name"=>"Huyện Long Thành","matp"=>"DONGNAI"),
    "539" => array("maqh"=>"741","name"=>"Huyện Xuân Lộc","matp"=>"DONGNAI"),
    "540" => array("maqh"=>"742","name"=>"Huyện Nhơn Trạch","matp"=>"DONGNAI"),
    "541" => array("maqh"=>"747","name"=>"Thành phố Vũng Tàu","matp"=>"BARIAVUNGTAU"),
    "542" => array("maqh"=>"748","name"=>"Thành phố Bà Rịa","matp"=>"BARIAVUNGTAU"),
    "543" => array("maqh"=>"750","name"=>"Huyện Châu Đức","matp"=>"BARIAVUNGTAU"),
    "544" => array("maqh"=>"751","name"=>"Huyện Xuyên Mộc","matp"=>"BARIAVUNGTAU"),
    "545" => array("maqh"=>"752","name"=>"Huyện Long Điền","matp"=>"BARIAVUNGTAU"),
    "546" => array("maqh"=>"753","name"=>"Huyện Đất Đỏ","matp"=>"BARIAVUNGTAU"),
    "547" => array("maqh"=>"754","name"=>"Thị xã Phú Mỹ","matp"=>"BARIAVUNGTAU"),
    "548" => array("maqh"=>"755","name"=>"Huyện Côn Đảo","matp"=>"BARIAVUNGTAU"),
    "549" => array("maqh"=>"760","name"=>"Quận 1","matp"=>"HOCHIMINH"),
    "550" => array("maqh"=>"761","name"=>"Quận 12","matp"=>"HOCHIMINH"),
    "551" => array("maqh"=>"764","name"=>"Quận Gò Vấp","matp"=>"HOCHIMINH"),
    "552" => array("maqh"=>"765","name"=>"Quận Bình Thạnh","matp"=>"HOCHIMINH"),
    "553" => array("maqh"=>"766","name"=>"Quận Tân Bình","matp"=>"HOCHIMINH"),
    "554" => array("maqh"=>"767","name"=>"Quận Tân Phú","matp"=>"HOCHIMINH"),
    "555" => array("maqh"=>"768","name"=>"Quận Phú Nhuận","matp"=>"HOCHIMINH"),
    "556" => array("maqh"=>"769","name"=>"Thành phố Thủ Đức","matp"=>"HOCHIMINH"),
    "557" => array("maqh"=>"770","name"=>"Quận 3","matp"=>"HOCHIMINH"),
    "558" => array("maqh"=>"771","name"=>"Quận 10","matp"=>"HOCHIMINH"),
    "559" => array("maqh"=>"772","name"=>"Quận 11","matp"=>"HOCHIMINH"),
    "560" => array("maqh"=>"773","name"=>"Quận 4","matp"=>"HOCHIMINH"),
    "561" => array("maqh"=>"774","name"=>"Quận 5","matp"=>"HOCHIMINH"),
    "562" => array("maqh"=>"775","name"=>"Quận 6","matp"=>"HOCHIMINH"),
    "563" => array("maqh"=>"776","name"=>"Quận 8","matp"=>"HOCHIMINH"),
    "564" => array("maqh"=>"777","name"=>"Quận Bình Tân","matp"=>"HOCHIMINH"),
    "565" => array("maqh"=>"778","name"=>"Quận 7","matp"=>"HOCHIMINH"),
    "566" => array("maqh"=>"783","name"=>"Huyện Củ Chi","matp"=>"HOCHIMINH"),
    "567" => array("maqh"=>"784","name"=>"Huyện Hóc Môn","matp"=>"HOCHIMINH"),
    "568" => array("maqh"=>"785","name"=>"Huyện Bình Chánh","matp"=>"HOCHIMINH"),
    "569" => array("maqh"=>"786","name"=>"Huyện Nhà Bè","matp"=>"HOCHIMINH"),
    "570" => array("maqh"=>"787","name"=>"Huyện Cần Giờ","matp"=>"HOCHIMINH"),
    "571" => array("maqh"=>"794","name"=>"Thành phố Tân An","matp"=>"LONGAN"),
    "572" => array("maqh"=>"795","name"=>"Thị xã Kiến Tường","matp"=>"LONGAN"),
    "573" => array("maqh"=>"796","name"=>"Huyện Tân Hưng","matp"=>"LONGAN"),
    "574" => array("maqh"=>"797","name"=>"Huyện Vĩnh Hưng","matp"=>"LONGAN"),
    "575" => array("maqh"=>"798","name"=>"Huyện Mộc Hóa","matp"=>"LONGAN"),
    "576" => array("maqh"=>"799","name"=>"Huyện Tân Thạnh","matp"=>"LONGAN"),
    "577" => array("maqh"=>"800","name"=>"Huyện Thạnh Hóa","matp"=>"LONGAN"),
    "578" => array("maqh"=>"801","name"=>"Huyện Đức Huệ","matp"=>"LONGAN"),
    "579" => array("maqh"=>"802","name"=>"Huyện Đức Hòa","matp"=>"LONGAN"),
    "580" => array("maqh"=>"803","name"=>"Huyện Bến Lức","matp"=>"LONGAN"),
    "581" => array("maqh"=>"804","name"=>"Huyện Thủ Thừa","matp"=>"LONGAN"),
    "582" => array("maqh"=>"805","name"=>"Huyện Tân Trụ","matp"=>"LONGAN"),
    "583" => array("maqh"=>"806","name"=>"Huyện Cần Đước","matp"=>"LONGAN"),
    "584" => array("maqh"=>"807","name"=>"Huyện Cần Giuộc","matp"=>"LONGAN"),
    "585" => array("maqh"=>"808","name"=>"Huyện Châu Thành","matp"=>"LONGAN"),
    "586" => array("maqh"=>"815","name"=>"Thành phố Mỹ Tho","matp"=>"TIENGIANG"),
    "587" => array("maqh"=>"816","name"=>"Thị xã Gò Công","matp"=>"TIENGIANG"),
    "588" => array("maqh"=>"817","name"=>"Thị xã Cai Lậy","matp"=>"TIENGIANG"),
    "589" => array("maqh"=>"818","name"=>"Huyện Tân Phước","matp"=>"TIENGIANG"),
    "590" => array("maqh"=>"819","name"=>"Huyện Cái Bè","matp"=>"TIENGIANG"),
    "591" => array("maqh"=>"820","name"=>"Huyện Cai Lậy","matp"=>"TIENGIANG"),
    "592" => array("maqh"=>"821","name"=>"Huyện Châu Thành","matp"=>"TIENGIANG"),
    "593" => array("maqh"=>"822","name"=>"Huyện Chợ Gạo","matp"=>"TIENGIANG"),
    "594" => array("maqh"=>"823","name"=>"Huyện Gò Công Tây","matp"=>"TIENGIANG"),
    "595" => array("maqh"=>"824","name"=>"Huyện Gò Công Đông","matp"=>"TIENGIANG"),
    "596" => array("maqh"=>"825","name"=>"Huyện Tân Phú Đông","matp"=>"TIENGIANG"),
    "597" => array("maqh"=>"829","name"=>"Thành phố Bến Tre","matp"=>"BENTRE"),
    "598" => array("maqh"=>"831","name"=>"Huyện Châu Thành","matp"=>"BENTRE"),
    "599" => array("maqh"=>"832","name"=>"Huyện Chợ Lách","matp"=>"BENTRE"),
    "600" => array("maqh"=>"833","name"=>"Huyện Mỏ Cày Nam","matp"=>"BENTRE"),
    "601" => array("maqh"=>"834","name"=>"Huyện Giồng Trôm","matp"=>"BENTRE"),
    "602" => array("maqh"=>"835","name"=>"Huyện Bình Đại","matp"=>"BENTRE"),
    "603" => array("maqh"=>"836","name"=>"Huyện Ba Tri","matp"=>"BENTRE"),
    "604" => array("maqh"=>"837","name"=>"Huyện Thạnh Phú","matp"=>"BENTRE"),
    "605" => array("maqh"=>"838","name"=>"Huyện Mỏ Cày Bắc","matp"=>"BENTRE"),
    "606" => array("maqh"=>"842","name"=>"Thành phố Trà Vinh","matp"=>"TRAVINH"),
    "607" => array("maqh"=>"844","name"=>"Huyện Càng Long","matp"=>"TRAVINH"),
    "608" => array("maqh"=>"845","name"=>"Huyện Cầu Kè","matp"=>"TRAVINH"),
    "609" => array("maqh"=>"846","name"=>"Huyện Tiểu Cần","matp"=>"TRAVINH"),
    "610" => array("maqh"=>"847","name"=>"Huyện Châu Thành","matp"=>"TRAVINH"),
    "611" => array("maqh"=>"848","name"=>"Huyện Cầu Ngang","matp"=>"TRAVINH"),
    "612" => array("maqh"=>"849","name"=>"Huyện Trà Cú","matp"=>"TRAVINH"),
    "613" => array("maqh"=>"850","name"=>"Huyện Duyên Hải","matp"=>"TRAVINH"),
    "614" => array("maqh"=>"851","name"=>"Thị xã Duyên Hải","matp"=>"TRAVINH"),
    "615" => array("maqh"=>"855","name"=>"Thành phố Vĩnh Long","matp"=>"VINHLONG"),
    "616" => array("maqh"=>"857","name"=>"Huyện Long Hồ","matp"=>"VINHLONG"),
    "617" => array("maqh"=>"858","name"=>"Huyện Mang Thít","matp"=>"VINHLONG"),
    "618" => array("maqh"=>"859","name"=>"Huyện Vũng Liêm","matp"=>"VINHLONG"),
    "619" => array("maqh"=>"860","name"=>"Huyện Tam Bình","matp"=>"VINHLONG"),
    "620" => array("maqh"=>"861","name"=>"Thị xã Bình Minh","matp"=>"VINHLONG"),
    "621" => array("maqh"=>"862","name"=>"Huyện Trà Ôn","matp"=>"VINHLONG"),
    "622" => array("maqh"=>"863","name"=>"Huyện Bình Tân","matp"=>"VINHLONG"),
    "623" => array("maqh"=>"866","name"=>"Thành phố Cao Lãnh","matp"=>"DONGTHAP"),
    "624" => array("maqh"=>"867","name"=>"Thành phố Sa Đéc","matp"=>"DONGTHAP"),
    "625" => array("maqh"=>"868","name"=>"Thành phố Hồng Ngự","matp"=>"DONGTHAP"),
    "626" => array("maqh"=>"869","name"=>"Huyện Tân Hồng","matp"=>"DONGTHAP"),
    "627" => array("maqh"=>"870","name"=>"Huyện Hồng Ngự","matp"=>"DONGTHAP"),
    "628" => array("maqh"=>"871","name"=>"Huyện Tam Nông","matp"=>"DONGTHAP"),
    "629" => array("maqh"=>"872","name"=>"Huyện Tháp Mười","matp"=>"DONGTHAP"),
    "630" => array("maqh"=>"873","name"=>"Huyện Cao Lãnh","matp"=>"DONGTHAP"),
    "631" => array("maqh"=>"874","name"=>"Huyện Thanh Bình","matp"=>"DONGTHAP"),
    "632" => array("maqh"=>"875","name"=>"Huyện Lấp Vò","matp"=>"DONGTHAP"),
    "633" => array("maqh"=>"876","name"=>"Huyện Lai Vung","matp"=>"DONGTHAP"),
    "634" => array("maqh"=>"877","name"=>"Huyện Châu Thành","matp"=>"DONGTHAP"),
    "635" => array("maqh"=>"883","name"=>"Thành phố Long Xuyên","matp"=>"ANGIANG"),
    "636" => array("maqh"=>"884","name"=>"Thành phố Châu Đốc","matp"=>"ANGIANG"),
    "637" => array("maqh"=>"886","name"=>"Huyện An Phú","matp"=>"ANGIANG"),
    "638" => array("maqh"=>"887","name"=>"Thị xã Tân Châu","matp"=>"ANGIANG"),
    "639" => array("maqh"=>"888","name"=>"Huyện Phú Tân","matp"=>"ANGIANG"),
    "640" => array("maqh"=>"889","name"=>"Huyện Châu Phú","matp"=>"ANGIANG"),
    "641" => array("maqh"=>"890","name"=>"Huyện Tịnh Biên","matp"=>"ANGIANG"),
    "642" => array("maqh"=>"891","name"=>"Huyện Tri Tôn","matp"=>"ANGIANG"),
    "643" => array("maqh"=>"892","name"=>"Huyện Châu Thành","matp"=>"ANGIANG"),
    "644" => array("maqh"=>"893","name"=>"Huyện Chợ Mới","matp"=>"ANGIANG"),
    "645" => array("maqh"=>"894","name"=>"Huyện Thoại Sơn","matp"=>"ANGIANG"),
    "646" => array("maqh"=>"899","name"=>"Thành phố Rạch Giá","matp"=>"KIENGIANG"),
    "647" => array("maqh"=>"900","name"=>"Thành phố Hà Tiên","matp"=>"KIENGIANG"),
    "648" => array("maqh"=>"902","name"=>"Huyện Kiên Lương","matp"=>"KIENGIANG"),
    "649" => array("maqh"=>"903","name"=>"Huyện Hòn Đất","matp"=>"KIENGIANG"),
    "650" => array("maqh"=>"904","name"=>"Huyện Tân Hiệp","matp"=>"KIENGIANG"),
    "651" => array("maqh"=>"905","name"=>"Huyện Châu Thành","matp"=>"KIENGIANG"),
    "652" => array("maqh"=>"906","name"=>"Huyện Giồng Riềng","matp"=>"KIENGIANG"),
    "653" => array("maqh"=>"907","name"=>"Huyện Gò Quao","matp"=>"KIENGIANG"),
    "654" => array("maqh"=>"908","name"=>"Huyện An Biên","matp"=>"KIENGIANG"),
    "655" => array("maqh"=>"909","name"=>"Huyện An Minh","matp"=>"KIENGIANG"),
    "656" => array("maqh"=>"910","name"=>"Huyện Vĩnh Thuận","matp"=>"KIENGIANG"),
    "657" => array("maqh"=>"911","name"=>"Thành phố Phú Quốc","matp"=>"KIENGIANG"),
    "658" => array("maqh"=>"912","name"=>"Huyện Kiên Hải","matp"=>"KIENGIANG"),
    "659" => array("maqh"=>"913","name"=>"Huyện U Minh Thượng","matp"=>"KIENGIANG"),
    "660" => array("maqh"=>"914","name"=>"Huyện Giang Thành","matp"=>"KIENGIANG"),
    "661" => array("maqh"=>"916","name"=>"Quận Ninh Kiều","matp"=>"CANTHO"),
    "662" => array("maqh"=>"917","name"=>"Quận Ô Môn","matp"=>"CANTHO"),
    "663" => array("maqh"=>"918","name"=>"Quận Bình Thuỷ","matp"=>"CANTHO"),
    "664" => array("maqh"=>"919","name"=>"Quận Cái Răng","matp"=>"CANTHO"),
    "665" => array("maqh"=>"923","name"=>"Quận Thốt Nốt","matp"=>"CANTHO"),
    "666" => array("maqh"=>"924","name"=>"Huyện Vĩnh Thạnh","matp"=>"CANTHO"),
    "667" => array("maqh"=>"925","name"=>"Huyện Cờ Đỏ","matp"=>"CANTHO"),
    "668" => array("maqh"=>"926","name"=>"Huyện Phong Điền","matp"=>"CANTHO"),
    "669" => array("maqh"=>"927","name"=>"Huyện Thới Lai","matp"=>"CANTHO"),
    "670" => array("maqh"=>"930","name"=>"Thành phố Vị Thanh","matp"=>"HAUGIANG"),
    "671" => array("maqh"=>"931","name"=>"Thành phố Ngã Bảy","matp"=>"HAUGIANG"),
    "672" => array("maqh"=>"932","name"=>"Huyện Châu Thành A","matp"=>"HAUGIANG"),
    "673" => array("maqh"=>"933","name"=>"Huyện Châu Thành","matp"=>"HAUGIANG"),
    "674" => array("maqh"=>"934","name"=>"Huyện Phụng Hiệp","matp"=>"HAUGIANG"),
    "675" => array("maqh"=>"935","name"=>"Huyện Vị Thuỷ","matp"=>"HAUGIANG"),
    "676" => array("maqh"=>"936","name"=>"Huyện Long Mỹ","matp"=>"HAUGIANG"),
    "677" => array("maqh"=>"937","name"=>"Thị xã Long Mỹ","matp"=>"HAUGIANG"),
    "678" => array("maqh"=>"941","name"=>"Thành phố Sóc Trăng","matp"=>"SOCTRANG"),
    "679" => array("maqh"=>"942","name"=>"Huyện Châu Thành","matp"=>"SOCTRANG"),
    "680" => array("maqh"=>"943","name"=>"Huyện Kế Sách","matp"=>"SOCTRANG"),
    "681" => array("maqh"=>"944","name"=>"Huyện Mỹ Tú","matp"=>"SOCTRANG"),
    "682" => array("maqh"=>"945","name"=>"Huyện Cù Lao Dung","matp"=>"SOCTRANG"),
    "683" => array("maqh"=>"946","name"=>"Huyện Long Phú","matp"=>"SOCTRANG"),
    "684" => array("maqh"=>"947","name"=>"Huyện Mỹ Xuyên","matp"=>"SOCTRANG"),
    "685" => array("maqh"=>"948","name"=>"Thị xã Ngã Năm","matp"=>"SOCTRANG"),
    "686" => array("maqh"=>"949","name"=>"Huyện Thạnh Trị","matp"=>"SOCTRANG"),
    "687" => array("maqh"=>"950","name"=>"Thị xã Vĩnh Châu","matp"=>"SOCTRANG"),
    "688" => array("maqh"=>"951","name"=>"Huyện Trần Đề","matp"=>"SOCTRANG"),
    "689" => array("maqh"=>"954","name"=>"Thành phố Bạc Liêu","matp"=>"BACLIEU"),
    "690" => array("maqh"=>"956","name"=>"Huyện Hồng Dân","matp"=>"BACLIEU"),
    "691" => array("maqh"=>"957","name"=>"Huyện Phước Long","matp"=>"BACLIEU"),
    "692" => array("maqh"=>"958","name"=>"Huyện Vĩnh Lợi","matp"=>"BACLIEU"),
    "693" => array("maqh"=>"959","name"=>"Thị xã Giá Rai","matp"=>"BACLIEU"),
    "694" => array("maqh"=>"960","name"=>"Huyện Đông Hải","matp"=>"BACLIEU"),
    "695" => array("maqh"=>"961","name"=>"Huyện Hoà Bình","matp"=>"BACLIEU"),
    "696" => array("maqh"=>"964","name"=>"Thành phố Cà Mau","matp"=>"CAMAU"),
    "697" => array("maqh"=>"966","name"=>"Huyện U Minh","matp"=>"CAMAU"),
    "698" => array("maqh"=>"967","name"=>"Huyện Thới Bình","matp"=>"CAMAU"),
    "699" => array("maqh"=>"968","name"=>"Huyện Trần Văn Thời","matp"=>"CAMAU"),
    "700" => array("maqh"=>"969","name"=>"Huyện Cái Nước","matp"=>"CAMAU"),
    "701" => array("maqh"=>"970","name"=>"Huyện Đầm Dơi","matp"=>"CAMAU"),
    "702" => array("maqh"=>"971","name"=>"Huyện Năm Căn","matp"=>"CAMAU"),
    "703" => array("maqh"=>"972","name"=>"Huyện Phú Tân","matp"=>"CAMAU"),
    "704" => array("maqh"=>"973","name"=>"Huyện Ngọc Hiển","matp"=>"CAMAU"),
);